server:
  port: 9090

#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: root
#    url: jdbc:postgresql://db:5432/SuManDB
#
#  jpa:
#    hibernate:
#      ddl-auto: update


spring:
  datasource:
    url: jdbc:h2:mem:suman
    driver-class-name: org.h2.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true