name: CI/CD Nicat

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
        working-directory: ./sumanback

      - name: Build with Gradle
        run: ./gradlew build -x test
        working-directory: ./sumanback

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t agilazizovf/sumanback .
        working-directory: ./sumanback

      - name: Push Docker Image
        run: docker push agilazizovf/sumanback
        working-directory: ./sumanback

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Ubuntu Server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull agilazizovf/sumanback
            docker stop sumanback || true
            docker rm sumanback || true
            docker run -d --name sumanback -p 9090:9090 agilazizovf/sumanback
